debug: false
page-helper:
  helperDialect: mysql
  reasonable: true
  defaultCount: true
logging:
  path: ${user.dir}
  level:
    web: debug
    io.seata: info
    org.apache.shardingsphere: debug
#  file:
#    name: myapp.log
spring:
  application:
    name: sharding-sphere-jdbc-demo
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:datasource-sharding.yaml
