debug: true
page-helper:
  helperDialect: mysql
  reasonable: true
  defaultCount: true
logging:
  path: ${user.dir}
server:
  port: 7770
spring:
  application:
    name: elastic-job-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  sql:
    init:
      mode: never
      encoding: utf-8
      schema-locations: classpath*:sql/init.sql
      username: root
      password: root
mybatis-plus:
  mapper-location: classpath*:com/example/elastic/job/demo/mapper/**/*.xml
  type-enums-package: com.example.elastic.job.demo.enums
elastic-job:
  regCenter:
    serverLists: 127.0.0.1:2181
    namespace: elastic-job-lite
  jobs:
    simpleJob:
#      job-error-handler-type: EMAIL
      job-sharding-strategy-type: AVG_ALLOCATION
      elastic-job-class: com.example.elastic.job.demo.jobs.MyJob
      cron: 0/10 * * * * ?
      time-zone: GMT+08:00
      sharding-total-count: 3
      sharding-item-parameters: 0=FEMALE,1=MALE,2=UNKNOW
      job-parameter: 0,1,2
      props:
        email.host: smtp.126.com
        email.port: 465
        email.username: tianrenshui1988@126.com
        email.password: xxxx
        email.from: tianrenshui1988@126.com
        email.to: 305744830@qq.com
        email.subject: "elastic job email test"
        email.debug: true
        email.useSsl: true
        email.ssl.trust: smtp.126.com
    dataflowJob:
      job-sharding-strategy-type: AVG_ALLOCATION
      elastic-job-class: com.example.elastic.job.demo.jobs.UserDataflowJob
      cron: 0/30 * * * * ?
      time-zone: GMT+08:00
      sharding-total-count: 3
      sharding-item-parameters: 0=FEMALE,1=MALE,2=UNKNOW
      job-parameter: 0,1,2
#    scriptJob:
#      elasticJobType: SCRIPT
#      cron: 0/10 * * * * ?
#      shardingTotalCount: 1
#      props:
#        script.command.line: "echo SCRIPT Job: "
#    manualScriptJob:
#      elasticJobType: SCRIPT
#      jobBootstrapBeanName: manualScriptJobBean
#      shardingTotalCount: 1
#      props:
#        script.command.line: "echo Manual SCRIPT Job: "
  tracing:
    type: RDB
#  echo "dump@simpleJob" | nc localhost 9999
  dump:
    port: 9999


