debug: true
page-helper:
  helperDialect: mysql
  reasonable: true
  defaultCount: true
logging:
  level:
    com.mysql.jc: trace
  file:
    name: myapp.log

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/sharding_db?useServerPrepStmts=true&cachePrepStmts=true
    username: root
    password: root